theme: jekyll-theme-minimal
title: Dromedary Drones (Team Cobalt)
description: ![build](https://github.com/Team-Cobalt/DromedaryDrones/workflows/build%20&%20test/badge.svg?branch=master)
![GitHub release](https://img.shields.io/github/v/release/Team-Cobalt/DromedaryDrones?include_prereleases) Team Cobalt's implementation of the Dromedary Drones project for COMP 350 B, Spring 2020.
